/* config.h.  Generated from config.h.in by configure.  */
/* config.h.in.  Generated from configure.in by autoheader.  */

/********************************************************************
* Description: config.h
*
*	Common defines used in many emc2 source files.
*       To add to this file, edit Section 4 in configure.in
*       and then run autoheader.
*
* Author: Autogenerated by autoheader
* License: LGPL Version 2
* System: Linux
*
* Copyright (c) 2004 All rights reserved.
********************************************************************/
#ifndef EMC2_CONFIG_H
#define EMC2_CONFIG_H

/* LINELEN is used throughout for buffer sizes, length of file name strings,
   etc. Let's just have one instead of a multitude of defines all the same. */
#define LINELEN 255
/* Used in a number of places for sprintf() buffers. */
#define BUFFERLEN 80

#define MM_PER_INCH 25.4
#define INCH_PER_MM (1.0/25.4)

/* RTAPI array sizes */
#define RTAPI_MAX_MODULES	64
#define RTAPI_MAX_TASKS		64
#define RTAPI_MAX_SHMEMS	32

#define MAX_INSTANCES           16

// default size of the HAL data segment
// can be overridden by the rtapi.so/ko module param hal_size=<n>
#define HAL_SIZE                262000

// minimum memlock limit
// see http://wiki.linuxcnc.org/cgi-bin/wiki.pl?LockedMemory
// edit /etc/security/limits.conf to read:
//  *       -    memlock 20480
#define RLIMIT_MEMLOCK_RECOMMENDED (20480*1024lu)

// default size of the thread stack size passed to rtapi_task_new()
// in hal_create_thread()
// can be overridden by an option to rtapi_msgd
#define HAL_STACKSIZE           32768

// a pseudo-flavor id to indicate ulapi<flavor>.so is not yet loaded
// not a build target, just a state indicator for ulapi_autoload.c
#define RTAPI_NOTLOADED_NAME  "not-yet-loaded"
#define RTAPI_NOTLOADED_ID    99

// format of zeroMQ IPC socket pathnames
// pass: RUNDIR, rtapi_instance, service name, uuid
// service name is: log, rtapi, halrcomp etc
#define ZMQIPC_FORMAT "ipc://%s/%d.%s.%s"


// flavor IDs for the various threads systems
// and conditional to set thread system and build_sys macros
// alter these in configure.in Subsection 2.0
#define RTAPI_POSIX_ID 0
#define RTAPI_POSIX_NAME "posix"
#define RTAPI_RT_PREEMPT_ID 1
#define RTAPI_RT_PREEMPT_NAME "rt-preempt"
#define RTAPI_XENOMAI_ID 2
#define RTAPI_XENOMAI_NAME "xenomai"
#define RTAPI_XENOMAI_KERNEL_ID 3
#define RTAPI_XENOMAI_KERNEL_NAME "xenomai-kernel"
#define RTAPI_RTAI_KERNEL_ID 4
#define RTAPI_RTAI_KERNEL_NAME "rtai-kernel"

#if ! defined(THREAD_FLAVOR_ID)
// this isn't allowed when building RTAPI
#ifdef RTAPI
#error RTAPI defined but THREAD_FLAVOR_ID not defined
#endif
#elif THREAD_FLAVOR_ID == RTAPI_POSIX_ID
#  define RTAPI_POSIX
#  define THREAD_FLAVOR_NAME "posix"
#  define BUILD_SYS_USER_DSO
#  define THREADS_HEADERS "rtapi/rt-preempt.h"
#elif THREAD_FLAVOR_ID == RTAPI_RT_PREEMPT_ID
#  define RTAPI_RT_PREEMPT
#  define THREAD_FLAVOR_NAME "rt-preempt"
#  define BUILD_SYS_USER_DSO
#  define THREADS_HEADERS "rtapi/rt-preempt.h"
#elif THREAD_FLAVOR_ID == RTAPI_XENOMAI_ID
#  define RTAPI_XENOMAI
#  define THREAD_FLAVOR_NAME "xenomai"
#  define BUILD_SYS_USER_DSO
#  define THREADS_HEADERS "rtapi/xenomai.h"
#elif THREAD_FLAVOR_ID == RTAPI_XENOMAI_KERNEL_ID
#  define RTAPI_XENOMAI_KERNEL
#  define THREAD_FLAVOR_NAME "xenomai-kernel"
#  define BUILD_SYS_KBUILD
#  define THREADS_HEADERS "rtapi/xenomai-kernel.h"
#elif THREAD_FLAVOR_ID == RTAPI_RTAI_KERNEL_ID
#  define RTAPI_RTAI_KERNEL
#  define THREAD_FLAVOR_NAME "rtai-kernel"
#  define BUILD_SYS_KBUILD
#  define THREADS_HEADERS "rtapi/rtai-kernel.h"
#else
#error unknown value for THREAD_FLAVOR_ID
#endif



/* build hardware drivers */
#define BUILD_DRIVERS /**/

/* build emcweb UI */
/* #undef BUILD_EMCWEB */

/* build programming examples */
/* #undef BUILD_EXAMPLES */

/* build NML dependent parts */
/* #undef BUILD_NMLDEP */

/* date when configure was run */
#define CONFIG_DATE "Feb  1 2015 12:39:55"

/* Directory for binaries */
#define EMC2_BIN_DIR "/usr/src/machinekit/bin"

/* Default nml file */
#define EMC2_DEFAULT_NMLFILE "/usr/src/machinekit/configs/common/linuxcnc.nml"

/* Default tooltable file */
#define EMC2_DEFAULT_TOOLTABLE "/usr/src/machinekit/configs/sim/sim.tbl"

/* Prefix or RIP directory */
#define EMC2_HOME "/usr/src/machinekit"

/* Directory for images */
#define EMC2_IMAGE_DIR "/usr/src/machinekit"

/* Directory for nc files */
#define EMC2_NCFILES_DIR "/usr/src/machinekit/nc_files"

/* Directory for po/mo translation files */
#define EMC2_PO_DIR "/usr/src/machinekit/share/locale"

/* Directory for ulapi shared objects */
#define EMC2_RTLIB_DIR "/usr/src/machinekit/rtlib"

/* SHA valid when configure was run */
#define GIT_CONFIG_SHA "fc2b850"

/* Git version tag */
#define GIT_VERSION "unknown"

/* avahi mDNS client library available */
#define HAVE_AVAHI /**/

/* Define to 1 if you have the <backtrace.h> header file. */
/* #undef HAVE_BACKTRACE_H */

/* define if the Boost library is available */
/* #undef HAVE_BOOST */

/* define if the Boost::Python headers and library are available */
#define HAVE_BOOST_PYTHON 1

/* define if the Boost::Serialization library is available */
/* #undef HAVE_BOOST_SERIALIZATION */

/* define if the Boost::System library is available */
/* #undef HAVE_BOOST_SYSTEM */

/* define if the Boost::Thread library is available */
/* #undef HAVE_BOOST_THREAD */

/* Define to 1 if you have the `clock_getres' function. */
#define HAVE_CLOCK_GETRES 1

/* define if the compiler supports basic C++11 syntax */
#define HAVE_CXX11 1

/* Build Cython-based Python extensions */
#define HAVE_CYTHON /**/

/* zeroMQ czmq library available */
#define HAVE_CZMQ /**/

/* Define to 1 if you have the <GL/glu.h> header file. */
#define HAVE_GL_GLU_H 1

/* Define to 1 if you have the <GL/gl.h> header file. */
#define HAVE_GL_GL_H 1

/* Define to 1 if you have the <inttypes.h> header file. */
/* #undef HAVE_INTTYPES_H */

/* jansson JSON C bindings available */
#define HAVE_JANSSON /**/

/* libbacktrace available */
/* #undef HAVE_LIBBACKTRACE */

/* Define to 1 if you have the <libbacktrace/backtrace.h> header file. */
/* #undef HAVE_LIBBACKTRACE_BACKTRACE_H */

/* Define to 1 if you have the `GL' library (-lGL). */
#define HAVE_LIBGL 1

/* Define to 1 if you have the `intl' library (-lintl). */
/* #undef HAVE_LIBINTL */

/* Define to 1 if you have the <libintl.h> header file. */
#define HAVE_LIBINTL_H 1

/* define if the libmodbus3 headers and library are available */
#define HAVE_LIBMODBUS3 yes

/* Define to 1 if you have the `ncurses' library (-lncurses). */
#define HAVE_LIBNCURSES 1

/* libudev installed and available */
#define HAVE_LIBUDEV /**/

/* define if the libusb-1.0 headers and library are available */
#define HAVE_LIBUSB10 yes

/* Define to 1 if you have the `Xaw' library (-lXaw). */
#define HAVE_LIBXAW 1

/* Define to 1 if you have the `Xinerama' library (-lXinerama). */
#define HAVE_LIBXINERAMA 1

/* Define to 1 if you have the <locale.h> header file. */
#define HAVE_LOCALE_H 1

/* libwebsockets library available */
#define HAVE_LWS /**/

/* Define to 1 if you have the <memory.h> header file. */
/* #undef HAVE_MEMORY_H */

/* Define to 1 if you have the <ncurses.h> header file. */
#define HAVE_NCURSES_H 1

/* Build POSIX threads */
#define HAVE_POSIX_THREADS /**/

/* zeroMQ czmq library available */
#define HAVE_PROTOBUF /**/

/* Define to 1 if you have the 'readline' library (-lreadline) and required
   headers */
#define HAVE_READLINE /**/

/* Define to 1 if you have the <readline/history.h> header file. */
#define HAVE_READLINE_HISTORY_H 1

/* Define to 1 if you have the <readline/readline.h> header file. */
#define HAVE_READLINE_READLINE_H 1

/* Build RTAI threads */
/* #undef HAVE_RTAI_KERNEL_THREADS */

/* Build RT_PREEMPT threads */
#define HAVE_RT_PREEMPT_THREADS /**/

/* Define to 1 if you have the `semtimedop' function. */
#define HAVE_SEMTIMEDOP 1

/* Define to 1 if you have the `setlocale' function. */
#define HAVE_SETLOCALE 1

/* Define to 1 if sincos is available. */
#define HAVE_SINCOS 1

/* libssl library available */
#define HAVE_SSL /**/

/* Define to 1 if you have the <stdint.h> header file. */
/* #undef HAVE_STDINT_H */

/* Define to 1 if you have the <stdlib.h> header file. */
/* #undef HAVE_STDLIB_H */

/* Define to 1 if you have the <strings.h> header file. */
/* #undef HAVE_STRINGS_H */

/* Define to 1 if you have the <string.h> header file. */
/* #undef HAVE_STRING_H */

/* Define to 1 if you have the <sys/stat.h> header file. */
/* #undef HAVE_SYS_STAT_H */

/* Define to 1 if you have the <sys/types.h> header file. */
/* #undef HAVE_SYS_TYPES_H */

/* Define to 1 if you have <sys/wait.h> that is POSIX.1 compatible. */
#define HAVE_SYS_WAIT_H 1

/* Define to 1 if you have the <tcl.h> header file. */
/* #undef HAVE_TCL_H */

/* Define to 1 if you have the <tk.h> header file. */
/* #undef HAVE_TK_H */

/* Define to 1 if you have the <unistd.h> header file. */
/* #undef HAVE_UNISTD_H */

/* uriparser library available */
#define HAVE_URIPARSER /**/

/* uuid library available */
#define HAVE_UUID /**/

/* Define to 1 if you have the <X11/extensions/Xinerama.h> header file. */
#define HAVE_X11_EXTENSIONS_XINERAMA_H 1

/* Define to 1 if you have the <X11/Xaw/XawInit.h> header file. */
#define HAVE_X11_XAW_XAWINIT_H 1

/* Define to 1 if you have the <X11/Xmu/Xmu.h> header file. */
#define HAVE_X11_XMU_XMU_H 1

/* Build Xenomai kernel threads */
/* #undef HAVE_XENOMAI_KERNEL_THREADS */

/* Build Xenomai userland threads */
/* #undef HAVE_XENOMAI_THREADS */

/* Define to 1 if you have the `__sincos' function. */
/* #undef HAVE___SINCOS */

/* Define to 1 if linux/hidraw.h is usable and defines HIDIOCGRAWINFO */
#define HIDRAW_H_USABLE /**/

/* path of global machinekit.ini file */
#define MACHINEKIT_INI "${prefix}/etc/linuxcnc/machinekit.ini"

/* Define to 1 if asm/msr.h is usable and defines rdtscll */
/* #undef MSR_H_USABLE */

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "emc-developers@lists.sourceforge.net"

/* Define to the full name of this package. */
#define PACKAGE_NAME "LinuxCNC"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "LinuxCNC 2.7.0~pre0"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "linuxcnc"

/* Define to the home page for this package. */
#define PACKAGE_URL ""

/* Define to the version of this package. */
#define PACKAGE_VERSION "2.7.0~pre0"

/* library pathname to LD_PRELOAD */
#define PRELOAD_WORKAROUND ""

/* directory for IPC sockets and other transient files */
#define RUNDIR "/tmp"

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* build for BeagleBone platform */
/* #undef TARGET_PLATFORM_BEAGLEBONE */

/* build for PC platform */
#define TARGET_PLATFORM_PC /**/

/* build for Raspberry Pi platform */
/* #undef TARGET_PLATFORM_RASPBERRY */

/* build PCI drivers with usermode PCI support */
#define USERMODE_PCI /**/

/* use ppdev ioctl instead of inb/outb */
/* #undef USE_PORTABLE_PARPORT_IO */

/* use shm driver module */
/* #undef USE_SHMDRV */

/* Define to 1 if the X Window System is missing or not being used. */
/* #undef X_DISPLAY_MISSING */

/* Enable GNU extensions on systems that have them.  */
#ifndef _GNU_SOURCE
# define _GNU_SOURCE
#endif


#endif

